[package]
name = "raptor"
version = "0.1.0"
edition = "2024"
authors = ["keogami <https://github.com/keogami>"]

[lib]
name = "raptor"
path = "src/lib.rs"

[dependencies]
gtfs-structures = "0.42"

[dev-dependencies]
anyhow = "1.0.100"

[profile.dev]
debug = "full"
